### ISSUE TITLE
What is eng_sig?

### ISSUE THREAD

**Issue by evautumn** [emyounglab/prymetime#35]
Hi, 
What is eng_sig? I have nanopore and illumina files, but not engineering signature files (and I'm not sure what exactly these are). I've looked for a description of this type of fasta file in your paper (https://www.nature.com/articles/s41467-021-21656-9#Sec11) and tried the read.me file, but I'm still not sure what the format of eng_sig is
Thank you,

**Comment by emyounglab** [comment]
Thanks for your question! The eng_sig file is intended to contain any FASTA sequences that you are interested in finding in your genome assembly. Since this was intended to be used with engineered yeast, we have a file that already contains some sequences.

We will discuss internally about updating Prymetime with an option to run without an eng_sig file, but for now you could likely 1) use the default eng_sig file we have on hand, it won't really make a difference for the assembly or 2) use a blank eng_sig file.

From: evautumn ***@***.***>
Sent: Thursday, March 3, 2022 4:18 PM
To: emyounglab/prymetime ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [EXT] [emyounglab/prymetime] What is eng_sig? (Issue #35)


Hi,
What is eng_sig? I have nanopore and illumina files, but not engineering signature files (and I'm not sure what exactly these are). I've looked for a description of this type of fasta file in your paper (https://www.nature.com/articles/s41467-021-21656-9#Sec11<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.nature.com%2Farticles%2Fs41467-021-21656-9%23Sec11&data=04%7C01%7Cemyoung%40wpi.edu%7Cde0c345f35914d452cef08d9fd5b3d6d%7C589c76f5ca1541f9884b55ec15a0672a%7C0%7C0%7C637819390577721241%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=DQVXpAkMbhy9ijrgMZX68S%2BG6eK1rLsFkrP2%2FdDImIo%3D&reserved=0>) and tried the read.me file, but I'm still not sure what eng_sig is and if it's essential. Is it possible to run prymetime with just nanopore and illumina files?
Thank you,

-
Reply to this email directly, view it on GitHub<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Femyounglab%2Fprymetime%2Fissues%2F35&data=04%7C01%7Cemyoung%40wpi.edu%7Cde0c345f35914d452cef08d9fd5b3d6d%7C589c76f5ca1541f9884b55ec15a0672a%7C0%7C0%7C637819390577721241%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Wnft%2FV2WPswk5AIAryGq9kzcSKyj1hj6ETlg5yL5wqA%3D&reserved=0>, or unsubscribe<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAOS5ILKW2A76M5BPIDHPD63U6ET67ANCNFSM5P3UQF6A&data=04%7C01%7Cemyoung%40wpi.edu%7Cde0c345f35914d452cef08d9fd5b3d6d%7C589c76f5ca1541f9884b55ec15a0672a%7C0%7C0%7C637819390577721241%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=hH5LnJyfM3WIabanw%2FkBmxfEsJmtl5wcUlaZVUF6NRg%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cemyoung%40wpi.edu%7Cde0c345f35914d452cef08d9fd5b3d6d%7C589c76f5ca1541f9884b55ec15a0672a%7C0%7C0%7C637819390577721241%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=jDAJwjG8nMTDZBEtx3Fu5lwabZzjWLPvTqdH%2BdDHwqw%3D&reserved=0> or Android<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cemyoung%40wpi.edu%7Cde0c345f35914d452cef08d9fd5b3d6d%7C589c76f5ca1541f9884b55ec15a0672a%7C0%7C0%7C637819390577721241%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=DucU1ORkhaitcMWBN61GujEsrV3evSNkNxoNUf6V%2F5M%3D&reserved=0>.
